name: CI/CD Ispace to GCP

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Ensure .env file exists
      run: |
        if [ ! -f .env ]; then
          cp .env.example .env
        fi
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest -f Dockerfile .
    
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
    
    - name: Upload .env file
      uses: actions/upload-artifact@v2
      with:
        name: env-file
        path: .env

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download .env file
      uses: actions/download-artifact@v2
      with:
        name: env-file
        path: .
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    
    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
    
    - name: Ensure Vendor and Storage Directories Exist
      run: |
        mkdir -p vendor storage/logs
        sudo chown -R $USER:$USER vendor storage
    
    - name: Install Composer Dependencies
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/var/www \
          -w /var/www \
          --env-file .env \
          --user root \
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
          sh -c "composer install --no-interaction --prefer-dist"
    
    - name: Generate APP_KEY
      run: |
       docker run --rm \
          -v $(pwd):/var/www \
          -w /var/www \
          --user root \
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
          sh -c "chown -R www-data:www-data storage bootstrap/cache && composer install && php artisan key:generate && php artisan test"
    
    - name: Run Docker Container and Execute Tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/var/www \
          -w /var/www \
          --env-file .env \
          --user root \
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
          php artisan test
    
    - name: Start Application for Accessibility Check
      run: |
        docker run -d --name my-app-container \
          -v ${{ github.workspace }}:/var/www \
          -w /var/www \
          --env-file .env \
          -p 8000:8000 \
          --user root \
          ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
          php artisan serve --host=0.0.0.0 --port=8000
    
    - name: Verify Application Accessibility
      run: |
        sleep 10 # Beri waktu untuk aplikasi berjalan
        curl -f http://localhost:8000 || exit 1
    
    - name: Cleanup
      run: docker rm -f my-app-container

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure GCP Credentials
      run: echo "${{ secrets.GCP_CREDENTIALS }}" > ${HOME}/gcp-credentials.json

    - name: Initialize Terraform
      run: terraform init
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Apply Terraform
      run: terraform apply -auto-approve -var="gcp_credentials_file=${HOME}/gcp-credentials.json" -var="project_id=ispacepso"
