name: Continuous Integration Dockerr

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Ensure .env file exists
      run: |
        if [ ! -f .env ]; then
          cp .env.example .env
        fi
    
    - name: Build Docker Image
      run: |
        docker build -t my-app:latest -f Dockerfile .

    - name: Upload .env file
      uses: actions/upload-artifact@v2
      with:
        name: env-file
        path: .env
    - name: Pull Docker Image
      run: |
        docker pull my-app:latest
        
  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download .env file
      uses: actions/download-artifact@v2
      with:
        name: env-file
        path: .

    - name: Run Docker Container and Execute Tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/var/www \
          -w /var/www \
          --env-file .env \
          my-app:latest \
          bash -c "composer install --no-interaction --prefer-dist && php artisan test"
