name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Ensure .env file
      run: |
        if [ ! -f .env ]; then
          echo "No .env file found, creating a new one."
          cp .env.example .env
        fi

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Upload .env file
      uses: actions/upload-artifact@v2
      with:
        name: env-file
        path: .env

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Download .env file
      uses: actions/download-artifact@v2
      with:
        name: env-file
        path: .

    - name: Verify .env file
      run: cat .env

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run Laravel Tests
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Download .env file
      uses: actions/download-artifact@v2
      with:
        name: env-file
        path: .

    - name: Install Composer Dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Run Laravel Server
      run: php artisan serve --host=0.0.0.0 --port=8000 &
    
    - name: Wait for Server to Start
      run: sleep 10
    
    - name: Test Application Running
      run: curl --fail http://localhost:8000
